interface=wlan0
domain=itarmy.box
local=/itarmy.box/
dhcp-range=10.10.10.10,10.10.10.200,255.255.255.0,12h
dhcp-option=option:router,10.10.10.1
dhcp-option=option:dns-server,10.10.10.1
address=/#/10.10.10.1
